@startuml

title git basics
!theme materia
title GIT Basics

component "github.com" #green {
    [origin repository] as origin
}

component "your PC" #silver{
    #lightblue[local repository] as local
    note left of local #DarkGray
        repository in the
        ".git" directory
    end note


    #orange[staging area] as stage
    note left of stage #DarkGray
        changes you marked
        for a commit
    end note

    [working directory] as wd
    note top of wd #DarkGray
        source code, all your
        directories and files
    end note
}



wd -[#orange]left-> stage : git add
stage -[#orange]up-> local : git commit
local -[#orange]up-> origin : git push

origin -[#green]down-> local : git clone or git pull
local -[#green]down-> wd : git checkout

@enduml